baseURL: "https://gdalba.github.io/essencias/"
title: Essências de Gabriel Dall'Alba
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Poesia
          url: poesia/
          weight: 5 
        - name: Filosofia
          url: filosofia/
        - name: Autor 
          url: sobre/
          weight: 2

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Essências
          subtitle: |
              <div style="font-size: 1.2rem !important; line-height: 1.8 !important; text-align: center !important;">
              Quero compartilhar minha poesia com um mundo que não toma forma através de pessoas.<br><br>
              
              Este espaço não é uma vitrine, é um abrigo.<br>
              
              Um abrigo para uma voz que desejou muito ser ouvida, envergonhada de tal desejo tão narcisista.<br>
              
              Aqui se arquivam as palavras que me escaparam da alma, as poesias, as filosofias, as essências.<br>
              
              Talvez se torne, cedo ou tarde, um arquivo de memórias póstumas.<br>
              
              Mas que sirva, enquanto durar, como uma oferenda à reflexão, ao resgate do sentir, à poesia em sua forma mais crua – nascida sem ornamento, sem intenção de agradar, apenas vinda da alma.
              </div>
          imageUrl: "Screenshot 2023-10-15 205624.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: "Poesia"
              url: poesia/
            - name: Filosofia
              url: filosofia/
            - name: Autor 
              url: sobre/

    # socialIcons: UNCOMMENT IF WANT TO USE SOCIAL ICONS
    #     - name: CV
    #       url: cv.pdf
    #     - name: Email
    #       url: mailto:igelfeld@regensburg.edu
    #     - name: Zoom
    #       url: https://www.zoom.us/my/igelfeld
    #     - name: Location
    #       url: location/
    #     - name: Office Hours
    #       url: officehours/
    #     - name: Google Scholar
    #       url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
    #     - name: GitHub
    #       url: https://github.com/pmichaillat
    #     - name: Substack
    #       url: https://pmichaillat.substack.com
    #     - name: YouTube
    #       url: https://www.youtube.com/@pmichaillat
    #     - name: Twitter
    #       url: https://x.com/pmichaillat
    #     - name: Bluesky
    #       url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Essências de Gabriel Dall'Alba"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2